### ISSUE TITLE
.editorconfig Solution Root

### ISSUE THREAD

**Issue by axylophon** [channeladam/ChannelAdam.CSharp.Snippets#1]
Hi :)
I have adopted your approach for distributing the .editorconfig file.
It is working perfectly fine, in each project directory there is now a .editorconfig file.

We are using SonarQube and want the external Roslyn Analyzer Rules also in the SonarQube analysis.
Unfortunately it is not working as the .editorconfig is only copied before build. But for SonarQube it must be there when running the SonarPrepare task...

Do you know a way to copy the .editorconfig files maybe when the packages are restored?

Thank you

**Comment by channeladam** [comment]
You could modify the Directory.Build.props to also copy the editorconfig file up a few levels to your solution folder

**Comment by axylophon** [comment]
Thank you for you answer!

Yeah but how do I find the solution folder.
Our repositories does not all have the same folder structure.

**Comment by channeladam** [comment]
Use this property function: https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#msbuild-getdirectorynameoffileabove

**Comment by axylophon** [comment]
Ok thank you very much that works but the root cause unfortunately is a different one.

When the editorconfig files are copied (directly before build) is too late. Is there a way to do it already when restoring the packages? Unfortunately i haven't found anything.

When preparing sonarqube the .editorconfig file must already be in place.

**Comment by channeladam** [comment]
You probably need to change when the CopyEditorConfig Target executes. 
In my snippets it runs BeforeBuild.
Change BeforeTargets to SonarPrepare?   (you mentioned SonarPrepare - I don't know details of SonarQube...)

Or otherwise try to find out when SonarCube happens and run CopeEditorConfig at another time - see these:
- https://docs.microsoft.com/en-us/visualstudio/msbuild/target-build-order?view=vs-2022#determine-the-target-build-order
- https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-specify-which-target-to-build-first?view=vs-2022

**Comment by axylophon** [comment]
Hi again, sorry for the delay but now I have a good solution for our workflow :)

In our Azure Devops Pipeline:

- first we restore the packages
- then we execute the target manually (copies files): dotnet msbuild /t:CopyEditorConfig
- then we run the SonarQubePrepare
- then building the solution

Now SonarQube is also importing the Roslyn Issues during analysis :)

Thanks you again for your support - very well done!
